import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import SiteHeader from "@/components/SiteHeader";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SiteHeader />
      <div className="container mx-auto max-w-4xl px-4 py-10">
        <Link href="/" className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline">
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </Link>

        <div className="mt-6 rounded-xl border border-border bg-card p-6 md:p-8">
          <h1 className="text-3xl font-bold text-primary">Privacy Policy</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: January 20, 2026</p>

          <p className="mt-6 text-sm leading-7">
            This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
            We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy.
          </p>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Interpretation and Definitions</h2>

            <h3 className="mt-4 text-base font-semibold">Interpretation</h3>
            <p className="mt-2 text-sm leading-7">
              The words of which the initial letter is capitalized have meanings defined under the following
              conditions. The following definitions shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>

            <h3 className="mt-4 text-base font-semibold">Definitions</h3>
            <p className="mt-2 text-sm leading-7">For the purposes of this Privacy Policy:</p>
            <ul className="mt-2 list-disc space-y-2 pl-6 text-sm leading-7">
              <li>
                <strong>Account</strong>: means a unique account created for You to access our Service or parts of our
                Service.
              </li>
              <li>
                <strong>Company</strong>: (referred to as either "the Company", "We", "Us", or "Our" in this
                Agreement) refers to Lawn Trooper.
              </li>
              <li>
                <strong>Cookies</strong>: are small files that are placed on Your computer, mobile device, or any
                other device by a website, containing the details of Your browsing history on that website among its
                many uses.
              </li>
              <li>
                <strong>Country</strong>: refers to Alabama, United States.
              </li>
              <li>
                <strong>Device</strong>: means any device that can access the Service such as a computer, a cellphone,
                or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong>: is any information that relates to an identified or identifiable
                individual.
              </li>
              <li>
                <strong>Service</strong>: refers to the Website.
              </li>
              <li>
                <strong>Service Provider</strong>: means any natural or legal person who processes the data on behalf
                of the Company. It refers to third-party companies or individuals employed by the Company to facilitate
                the Service, to provide the Service on behalf of the Company, to perform services related to the
                Service, or to assist the Company in analyzing how the Service is used.
              </li>
              <li>
                <strong>Usage Data</strong>: refers to data collected automatically, either generated by the use of the
                Service or from the Service infrastructure itself (for example, the duration of a page visit).
              </li>
              <li>
                <strong>Website</strong>: refers to Lawn Trooper, accessible from{" "}
                <a href="https://www.thelawntrooper.com" className="text-primary underline" target="_blank" rel="noreferrer">
                  www.thelawntrooper.com
                </a>
                .
              </li>
              <li>
                <strong>You</strong>: means the individual accessing or using the Service, or the company, or other
                legal entity on behalf of which such individual is accessing or using the Service, as applicable.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Data Sharing</h2>
            <p className="mt-2 text-sm leading-7">
              No mobile information will be shared with third parties/affiliates for marketing/promotional purposes.
              Information sharing to subcontractors in support services, such as customer service, is permitted. All
              other use case categories exclude text messaging originator opt-in data and consent; this information
              will not be shared with any third parties.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Collecting and Using Your Personal Data</h2>
            <h3 className="mt-4 text-base font-semibold">Types of Data Collected</h3>
            <h4 className="mt-3 text-sm font-semibold">Personal Data</h4>
            <p className="mt-2 text-sm leading-7">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information
              that can be used to contact or identify You. Personally identifiable information may include, but is not
              limited to:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-6 text-sm leading-7">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="mt-5 text-sm font-semibold">SMS Opt-In Details</h4>
            <p className="mt-2 text-sm leading-7">
              If you provide your phone number through our website forms, estimate requests, service sign-ups, or
              other communication channels, you may opt in to receive SMS (text) messages from Lawn Trooper.
            </p>
            <p className="mt-2 text-sm leading-7">
              These messages may include appointment reminders, service updates, billing notifications, and promotional
              offers (if opted in). Message frequency may vary. Message and data rates may apply depending on your
              mobile carrier.
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-6 text-sm leading-7">
              <li>You may opt out of SMS communications at any time by replying STOP to any message.</li>
              <li>Reply HELP for assistance.</li>
              <li>Consent to receive SMS messages is not a condition of purchase.</li>
            </ul>

            <h4 className="mt-5 text-sm font-semibold">Usage Data</h4>
            <p className="mt-2 text-sm leading-7">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="mt-2 text-sm leading-7">
              Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP
              address), browser type, browser version, the pages of our Service that You visit, the time and date of
              Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
            </p>
            <p className="mt-2 text-sm leading-7">
              When You access the Service by or through a mobile device, We may collect certain information
              automatically, including, but not limited to, the type of mobile device You use, Your mobile device
              unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
              Internet browser You use, unique device identifiers, and other diagnostic data.
            </p>
            <p className="mt-2 text-sm leading-7">
              We may also collect information that Your browser sends whenever You visit our Service or when You access
              the Service by or through a mobile device.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Tracking Technologies and Cookies</h2>
            <p className="mt-2 text-sm leading-7">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
              information. Tracking technologies used are beacons, tags, and scripts to collect and track information
              and to improve and analyze Our Service.
            </p>
            <p className="mt-2 text-sm leading-7">The technologies We use may include:</p>
            <ul className="mt-2 list-disc space-y-2 pl-6 text-sm leading-7">
              <li>
                <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can
                instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You
                do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted
                Your browser setting so that it will refuse Cookies, our Service may use Cookies.
              </li>
              <li>
                <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small
                electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel
                gifs) that permit the Company, for example, to count users who have visited those pages or opened an
                email and for other related website statistics (for example, recording the popularity of a certain
                section and verifying system and server integrity).
              </li>
            </ul>
            <p className="mt-2 text-sm leading-7">
              Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your
              personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You
              close Your web browser.
            </p>
            <p className="mt-2 text-sm leading-7">
              We use both Session and Persistent Cookies for the purposes set out below:
            </p>
            <ul className="mt-2 list-disc space-y-2 pl-6 text-sm leading-7">
              <li>
                <strong>Necessary / Essential Cookies</strong> - Type: Session Cookies - Administered by: Us -
                Purpose: These Cookies are essential to provide You with services available through the Website and to
                enable You to use some of its features.
              </li>
              <li>
                <strong>Cookies Policy / Notice Acceptance Cookies</strong> - Type: Persistent Cookies - Administered
                by: Us - Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
              </li>
              <li>
                <strong>Functionality Cookies</strong> - Type: Persistent Cookies - Administered by: Us - Purpose:
                These Cookies allow us to remember choices You make when You use the Website.
              </li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Use of Your Personal Data</h2>
            <p className="mt-2 text-sm leading-7">The Company may use Personal Data for the following purposes:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6 text-sm leading-7">
              <li>To provide and maintain our Service, including to monitor usage of our Service.</li>
              <li>To manage Your Account and user registration.</li>
              <li>For the performance of a contract.</li>
              <li>To contact You by email, phone calls, SMS, or similar electronic communications.</li>
              <li>To provide news, special offers, and general information unless You opt out.</li>
              <li>To manage Your requests.</li>
              <li>For business transfers such as merger, acquisition, or asset sale.</li>
              <li>For analytics and improvement of Service, products, services, and marketing.</li>
              <li>With Your consent for any other purpose.</li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Retention of Your Personal Data</h2>
            <p className="mt-2 text-sm leading-7">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in
              this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our
              legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p className="mt-2 text-sm leading-7">
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained
              for a shorter period of time, except when this data is used to strengthen security, improve
              functionality, or when legally required to keep it longer.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Transfer of Your Personal Data</h2>
            <p className="mt-2 text-sm leading-7">
              Your information, including Personal Data, is processed at the Company&apos;s operating offices and in
              any other places where the parties involved in the processing are located. This means that information
              may be transferred to and maintained on computers located outside of Your state, province, country, or
              other governmental jurisdiction where data protection laws may differ.
            </p>
            <p className="mt-2 text-sm leading-7">
              Your consent to this Privacy Policy followed by Your submission of such information represents Your
              agreement to that transfer.
            </p>
            <p className="mt-2 text-sm leading-7">
              The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
              accordance with this Privacy Policy.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Delete Your Personal Data</h2>
            <p className="mt-2 text-sm leading-7">
              You have the right to delete or request that We assist in deleting the Personal Data that We have
              collected about You.
            </p>
            <p className="mt-2 text-sm leading-7">
              Our Service may give You the ability to delete certain information about You from within the Service.
            </p>
            <p className="mt-2 text-sm leading-7">
              You may update, amend, or delete Your information at any time by signing in to Your Account (if you have
              one) and visiting the account settings section. You may also contact Us to request access to, correction
              of, or deletion of personal information You have provided to Us.
            </p>
            <p className="mt-2 text-sm leading-7">
              Please note that We may need to retain certain information when we have a legal obligation or lawful
              basis to do so.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Disclosure of Your Personal Data</h2>
            <h3 className="mt-4 text-base font-semibold">Business Transactions</h3>
            <p className="mt-2 text-sm leading-7">
              If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be
              transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a
              different Privacy Policy.
            </p>
            <h3 className="mt-4 text-base font-semibold">Law Enforcement</h3>
            <p className="mt-2 text-sm leading-7">
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required by
              law or in response to valid requests by public authorities.
            </p>
            <h3 className="mt-4 text-base font-semibold">Other Legal Requirements</h3>
            <p className="mt-2 text-sm leading-7">
              The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-6 text-sm leading-7">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Security of Your Personal Data</h2>
            <p className="mt-2 text-sm leading-7">
              The security of Your Personal Data is important to Us, but no method of transmission over the Internet,
              or method of electronic storage, is 100% secure. While We strive to use commercially acceptable means to
              protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Children&apos;s Privacy</h2>
            <p className="mt-2 text-sm leading-7">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally
              identifiable information from anyone under the age of 13.
            </p>
            <p className="mt-2 text-sm leading-7">
              If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data,
              please contact Us. If We become aware that We have collected Personal Data from anyone under 13 without
              verification of parental consent, We take steps to remove that information.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Links to Other Websites</h2>
            <p className="mt-2 text-sm leading-7">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third
              party link, You will be directed to that third party&apos;s site. We strongly advise You to review the
              Privacy Policy of every site You visit.
            </p>
            <p className="mt-2 text-sm leading-7">
              We have no control over and assume no responsibility for the content, privacy policies, or practices of
              any third-party sites or services.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Mobile Information Sharing Statement</h2>
            <p className="mt-2 text-sm leading-7">
              No mobile information will be shared with third parties or affiliates for marketing or promotional
              purposes. All categories exclude text messaging originator opt-in data and consent; this information will
              not be shared with any third parties.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Changes to This Privacy Policy</h2>
            <p className="mt-2 text-sm leading-7">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
              Privacy Policy on this page.
            </p>
            <p className="mt-2 text-sm leading-7">
              We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming
              effective, and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
            </p>
            <p className="mt-2 text-sm leading-7">
              You are advised to review this Privacy Policy periodically for any changes. Changes are effective when
              they are posted on this page.
            </p>
          </section>

          <section className="mt-8">
            <h2 className="text-xl font-semibold text-primary">Contact Us</h2>
            <p className="mt-2 text-sm leading-7">For any questions regarding this Privacy Policy, please contact us:</p>
            <div className="mt-3 space-y-1 text-sm leading-7">
              <p>LAWN TROOPER LLC</p>
              <p>Phone: (256) 874-2059</p>
              <p>
                Email:{" "}
                <a href="mailto:john@thelawntrooper.com" className="text-primary underline">
                  john@thelawntrooper.com
                </a>
              </p>
              <p>
                Website:{" "}
                <a href="https://thelawntrooper.com" className="text-primary underline" target="_blank" rel="noreferrer">
                  thelawntrooper.com
                </a>
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
